version: '3'

services:

  dataanalises:
    container_name: dataanalises 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      #- CHOKIDAR_USEPOLLING="true"
      #- WATCHPACK_POLLING=true
      #- FAST_REFRESH=false
      - WDS_SOCKET_PORT=3001
