pipeline {
    agent any

    stages {
        stage ('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("caco21/dataanalises_backend:${env.BUILD_NUMBER}", '-f ./backend/dataanalises/Dockerfile_k8s ./backend/dataanalises')
                }
            }
        }
    }
}
