pipeline {
    agent any

    stages {
        stage ('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("caco21/dataanalises_backend:${env.BUILD_NUMBER}", '-f ./backend/dataanalises/Dockerfile_k8s ./backend/dataanalises')
                }
            }
        }
        stage ('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_NUMBER}")
                    }
                }
            }
        }
        stage ('Deploy Kubernetes') {
            steps {
                script {
                    withKubeconfig ([credentialsId: 'kubeconfig']) {
                        sh 'kubectl apply -f ./k8s/deployment_aws.yml'
                    }
                }
            }
        }
    }
}
